### PR TITLE
update navigation

### PR DESCRIPTION
**Pull request by CyberJJ19**
add / tweaks the navigation system

### CODE REVIEW

**Comment by jcmundy** [comment]
We're not updating Rob's branch anymore - Kevin's is the official code.  We should cancel this pull request.

**Comment by CyberJJ19** [comment]
Oh Okay thank for the reminder I will cancel the pull
J ***@***.***>于2021年5月4日 周二下午2:02写道：

**Comment by CyberJJ19** [comment]
How can I cancel the pull request ?
jinsong jiang ***@***.***>于2021年5月4日 周二下午2:04写道：

**Comment by jcmundy** [comment]
There should be a 'close pull request' button at the bottom: https://stackoverflow.com/questions/5385567/how-to-cancel-a-pull-request-on-github

**Comment by CyberJJ19** [comment]
Thank you I have cancel it

J ***@***.***> 于2021年5月4日周二 下午2:11写道：

**Pull request closed without merging**
